---
language: ruby
rvm:
  - 2.3.3
  - 2.5.1
script:
  - 'bundle exec rake syntax lint spec'
env:
  - PUPPET_VERSION=4.10.0
  - PUPPET_VERSION=5.5.6
branches:
  only:
    - master
notifications:
  email: false
